### ISSUE TITLE
Add Bun runtime support

### ISSUE THREAD

**Issue by Duckinm** [SuhelMakkad/vscode-shadcn-ui#2]

**Comment by SuhelMakkad** [comment]
Hey @Duckinm, check this #1

**Comment by Duckinm** [comment]
Oh, too fast! Thank you

**Comment by SuhelMakkad** [comment]
Hey @Duckinm, 0.0.301 is published https://marketplace.visualstudio.com/items?itemName=SuhelMakkad.shadcn-ui please check it out.

Start and a rating will be appreciated 😊
